import Head from "next/head";
import { ReactElement } from "react";
import type { NextPageWithLayout } from "../_app";
import styles from "../../styles/account/account.module.scss";
import useSWR from "swr";
import { useRouter } from "next/router";
import classNames from "classnames/bind";
import AccountForm from "@/components/_account-page/account-form/account-form";
import AccountLayout from "@/components/account-layout/account-layout";

let cx = classNames.bind(styles);

// const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Account: NextPageWithLayout = () => {
  const { pathname, asPath, push, isReady } = useRouter();

  console.log(asPath, pathname);

  // const { data, error, isLoading } = useSWR<RestaurantRes[]>(
  //   "/api" + asPath,
  //   fetcher
  // );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountForm />
    </>
  );
};

Account.getLayout = function getLayout(page: ReactElement) {
  return <AccountLayout>{page}</AccountLayout>;
};

export default Account;
