export const ADD_MODAL_INFO = "ADD_MODAL_INFO";
export const DELETE_MODAL_INFO = "DELETE_MODAL_INFO";

export const SET_EXAMPLE_MOD = "SET_EXAMPLE_MOD";
export const DELETE_EXAMPLE_MOD = "DELETE_EXAMPLE_MOD";
