import Header from "../components/header/header";
import Head from "next/head";
import { ReactElement } from "react";
import Layout from "../components/layout/layout";
import type { NextPageWithLayout } from "./_app";
import Promo from "../components/promo/promo";
import styles from "../styles/home.module.scss";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <section className={styles.promo}>
          <Promo
            img={"/promo-deserts.png"}
            alt={"Desserts"}
            mod={"primary"}
            title={"All deserts"}
            info={"20% OFF"}
            category={"Desserts"}
          />
          <Promo
            img={"/promo-burgers.png"}
            alt={"Burgers"}
            mod={"secondary"}
            title={"Big Burgers"}
            info={"50% OFF"}
            category={"Fooddies"}
          />
        </section>
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
