import AuthLayout from "@/components/_layouts/auth-layout/auth-layout";
import LoginForm, {
  LoginInputValues,
} from "@/components/_common/login-form/login-form";
import Logo from "@/components/_common/logo/logo";
import Head from "next/head";
import Link from "next/link";
import { ReactElement } from "react";
import styles from "../styles/login.module.scss";
import { useAuth } from "@/hooks/use-auth";
import { useAppState } from "@/hooks/use-app-state";
import { ADD_MODAL_INFO } from "@/services/actions/actions";

const Login = () => {
  const { signIn } = useAuth();
  const { dispatch } = useAppState();

  const handleLoginSubmit = async (formData: LoginInputValues) => {
    const { email, password } = formData;

    try {
      await signIn(email, password);
    } catch (error: any) {
      dispatch({
        type: ADD_MODAL_INFO,
        payload: { type: "error", info: error },
      });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Link href={"/"} className={styles.logo}>
          <Logo />
        </Link>
        <LoginForm mix={styles["login-form"]} onSubmit={handleLoginSubmit} />
      </div>
    </>
  );
};

Login.getLayout = function getLayout(page: ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
};

export default Login;
