import AuthLayout from "@/components/auth-layout/auth-layout";
import LoginForm from "@/components/_common/login-form/login-form";
import Logo from "@/components/_common/logo/logo";
import Head from "next/head";
import Link from "next/link";
import { ReactElement } from "react";
import styles from "../styles/login.module.scss";

const Login = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Link href={"/"} className={styles.logo}>
          <Logo />
        </Link>
        <LoginForm mix={styles["login-form"]} />
      </div>
    </>
  );
};

Login.getLayout = function getLayout(page: ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
};

export default Login;
