import AuthLayout from "@/components/_layouts/auth-layout/auth-layout";
import Logo from "@/components/_common/logo/logo";
import Head from "next/head";
import { ReactElement } from "react";
import styles from "../styles/recover.module.scss";
import Link from "next/link";
import RecoverForm, {
  RecoverInputValues,
} from "@/components/_common/recover-form/recover-form";
import { useAuth } from "@/hooks/useAuth";

const Recover = () => {
  const { user, auth, resetPassword } = useAuth();

  const handleRecoverSubmit = async (formData: RecoverInputValues) => {
    const { email } = formData;

    try {
      await resetPassword(email);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Link href={"/"}>
          <Logo />
        </Link>
        <RecoverForm
          mix={styles["recover-form"]}
          onSubmit={handleRecoverSubmit}
        />
      </div>
    </>
  );
};

Recover.getLayout = function getLayout(page: ReactElement) {
  return <AuthLayout>{page}</AuthLayout>;
};

export default Recover;
